DmlDemo.dmlMultipleRecordUpdate_right2();
DmlDemo.dmlMultipleRecordUpdate_right1();
DmlDemo.dmlMultipleRecordInsert_right2();
DmlDemo.dmlMultipleRecordInsert_right1();
DmlDemo.dmlInsertDemo_wrong1();
DmlDemo.dmlInsertDemo_cstmObj2();
DmlDemo.dmlInsertDemo_stndObj();
DmlDemo.dmlInsertDemo_cstmObj();
DmlDemo.dmlupdateDemo_stndObj1();
DmlDemo.dmlUpdateDemo_stndObj3();
DmlDemo.dmlInsertDemo_stndObj2();


delete [select id from account where createddate = TODAY limit 50];