List<integer> listInteger = new List<integer>();
listInteger.add(100);
listInteger.add(415);
listInteger.add(2881);
listInteger.add(1445);
listInteger.add(175);
integer sumofList = ListDemo.add(listInteger);
system.debug('sum of list is ' + sumofList);



ListDemo.iterateListInteger();
ListDemo.allCats();
string c2 = ListDemo.candidatesList(2);
system.debug('c2 ==> ' + c2);
string c5 = ListDemo.candidatesList(5);
system.debug('c5 ==> ' + c5);


ListDemo.randomIntegerList();

